//! REGION.TXT uses visible polygons, independently of opaque BMP artwork.
//! Studio emits disjoint rectangles: Audacious treats every polygon as its bounds.
use anyhow::{ensure, Context, Result};
use serde::Serialize;
use std::collections::BTreeMap;
pub const SECTIONS: [&str; 4] = ["Normal", "WindowShade", "Equalizer", "EqualizerWS"];
pub const MAX_VALUE_BYTES: usize = 65530; // Winamp's INI reader has a 65535-byte buffer.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize)]
pub struct Regions {
    pub sections: BTreeMap<String, Vec<Vec<[i32; 2]>>>,
}
impl Regions {
    pub fn parse(bytes: &[u8]) -> Result<Self> {
        let text = super::decode_text(bytes);
        let mut entries: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
        let mut section = None;
        for raw in text.trim_start_matches('﻿').lines() {
            let line = raw.split(';').next().unwrap_or("").trim();
            if line.is_empty() || line.starts_with("//") {
                continue;
            }
            if let Some(name) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                section = SECTIONS
                    .iter()
                    .find(|s| s.eq_ignore_ascii_case(name.trim()))
                    .copied();
                continue;
            }
            let Some(section) = section else { continue };
            let Some((key, value)) = line.split_once('=') else {
                anyhow::bail!("[{section}] requires one-line NumPoints and PointList values")
            };
            let key = key.trim().to_ascii_lowercase();
            if key != "numpoints" && key != "pointlist" {
                continue;
            }
            ensure!(
                value.len() <= MAX_VALUE_BYTES,
                "[{section}] {key} exceeds Winamp's INI buffer"
            );
            let previous = entries
                .entry(section.into())
                .or_default()
                .insert(key.clone(), value.trim().into());
            ensure!(
                previous.is_none(),
                "Duplicate [{section}] {key} is ambiguous between players"
            );
        }
        let numbers = |s: &str| -> Result<Vec<i32>> {
            s.split(|c: char| c == ',' || c.is_ascii_whitespace())
                .filter(|s| !s.is_empty())
                .map(|s| {
                    s.parse()
                        .with_context(|| format!("Invalid region coordinate {s}"))
                })
                .collect()
        };
        let mut result = Self::default();
        for (section, values) in entries {
            let counts = numbers(values.get("numpoints").context("Missing NumPoints")?)?;
            let points = numbers(values.get("pointlist").context("Missing PointList")?)?;
            if counts.is_empty() && points.is_empty() {
                continue;
            }
            ensure!(
                counts.iter().all(|n| *n >= 3 && *n <= 16384),
                "[{section}] polygons need 3..16384 points"
            );
            ensure!(
                counts.iter().map(|n| *n as usize).sum::<usize>() * 2 == points.len(),
                "[{section}] NumPoints does not match PointList"
            );
            ensure!(
                points.iter().all(|v| (-32768..=32767).contains(v)),
                "Region coordinate outside supported range"
            );
            let mut offset = 0;
            let mut polygons = Vec::new();
            for count in counts {
                let end = offset + count as usize * 2;
                polygons.push(
                    points[offset..end]
                        .as_chunks::<2>()
                        .0
                        .iter()
                        .map(|p| [p[0], p[1]])
                        .collect(),
                );
                offset = end;
            }
            result.sections.insert(section, polygons);
        }
        Ok(result)
    }
    pub fn encode(&self) -> Result<Vec<u8>> {
        let mut text =
            String::from("; Visible window pixels. Generated by Cranamp Skin Studio.\r\n");
        for name in SECTIONS {
            let Some(polygons) = self.sections.get(name) else {
                continue;
            };
            ensure!(
                !polygons.is_empty(),
                "An empty region is interpreted as a full window; keep at least one visible pixel"
            );
            let counts = polygons
                .iter()
                .map(|p| p.len().to_string())
                .collect::<Vec<_>>()
                .join(",");
            let points = polygons
                .iter()
                .flatten()
                .flatten()
                .map(i32::to_string)
                .collect::<Vec<_>>()
                .join(",");
            ensure!(
                counts.len() <= MAX_VALUE_BYTES && points.len() <= MAX_VALUE_BYTES,
                "Region is too complex for Winamp's INI buffer; simplify the mask"
            );
            text.push_str(&format!(
                "[{name}]\r\nNumPoints={counts}\r\nPointList={points}\r\n"
            ));
        }
        Self::parse(text.as_bytes())?;
        Ok(text.into_bytes())
    }
    pub fn mask(&self, name: &str, width: u32, height: u32) -> Vec<bool> {
        let Some(polygons) = self.sections.get(name) else {
            return vec![true; (width * height) as usize];
        };
        // Nonzero winding, as used by Winamp's CreatePolyPolygonRgn. Work on
        // native pixel centers; generated integer rectangles have exact edges.
        (0..height)
            .flat_map(|y| {
                (0..width).map(move |x| {
                    let (px, py) = (f64::from(x) + 0.5, f64::from(y) + 0.5);
                    let mut winding = 0i32;
                    for polygon in polygons {
                        for i in 0..polygon.len() {
                            let a = polygon[i];
                            let b = polygon[(i + 1) % polygon.len()];
                            let side = f64::from(b[0] - a[0]) * (py - f64::from(a[1]))
                                - (px - f64::from(a[0])) * f64::from(b[1] - a[1]);
                            if f64::from(a[1]) <= py && f64::from(b[1]) > py && side > 0.0 {
                                winding += 1;
                            }
                            if f64::from(a[1]) > py && f64::from(b[1]) <= py && side < 0.0 {
                                winding -= 1;
                            }
                        }
                    }
                    winding != 0
                })
            })
            .collect()
    }
    pub fn set_mask(&mut self, name: &str, width: u32, height: u32, mask: &[bool]) -> Result<()> {
        ensure!(SECTIONS.contains(&name), "Unknown classic region {name}");
        ensure!(
            width == 275
                && height
                    == if name.ends_with("Shade") || name.ends_with("WS") {
                        14
                    } else {
                        116
                    },
            "Region size must match its classic window"
        );
        ensure!(
            mask.len() == (width * height) as usize,
            "Region mask size mismatch"
        );
        ensure!(
            mask.iter().any(|p| *p),
            "A whole invisible window is not portable"
        );
        let polygons = rectangles(mask, width, height, true)
            .into_iter()
            .map(|[x, y, w, h]| vec![[x, y], [x + w, y], [x + w, y + h], [x, y + h]])
            .collect();
        self.sections.insert(name.into(), polygons);
        self.encode()?;
        Ok(())
    }
    pub fn portable(&self) -> bool {
        for polygons in self.sections.values() {
            let mut orientation = 0;
            for p in polygons {
                let area: i64 = (0..p.len())
                    .map(|i| {
                        let a = p[i];
                        let b = p[(i + 1) % p.len()];
                        i64::from(a[0]) * i64::from(b[1]) - i64::from(b[0]) * i64::from(a[1])
                    })
                    .sum();
                if area == 0 || (orientation != 0 && area.signum() != orientation) {
                    return false;
                }
                orientation = area.signum();
            }
        }
        // A polygon's coverage must equal its bounding rectangle in every player.
        self.sections.values().flatten().all(|p| {
            if p.len() != 4 {
                return false;
            }
            (0..4).all(|i| {
                let a = p[i];
                let b = p[(i + 1) % 4];
                (a[0] == b[0]) != (a[1] == b[1])
            })
        })
    }
}
/// Merge equal horizontal runs vertically, producing disjoint exact rectangles.
pub fn rectangles(mask: &[bool], width: u32, height: u32, value: bool) -> Vec<[i32; 4]> {
    let mut result: Vec<[i32; 4]> = Vec::new();
    let mut previous: BTreeMap<(u32, u32), usize> = BTreeMap::new();
    for y in 0..height {
        let mut current = BTreeMap::new();
        let mut x = 0;
        while x < width {
            if mask[(y * width + x) as usize] != value {
                x += 1;
                continue;
            }
            let start = x;
            while x < width && mask[(y * width + x) as usize] == value {
                x += 1;
            }
            let key = (start, x - start);
            let index = if let Some(index) = previous.get(&key).copied() {
                result[index][3] += 1;
                index
            } else {
                result.push([start as i32, y as i32, (x - start) as i32, 1]);
                result.len() - 1
            };
            current.insert(key, index);
        }
        previous = current;
    }
    result
}
#[cfg(test)]
#[path = "../../../test/unit/winamp/skin/regions_tests.rs"]
mod tests;
